### ISSUE TITLE
Tracking Issue

### ISSUE THREAD

**Issue by DjDeveloperr** [littledivy/napi-rusty-v8#5]
- [x] Environment life cycle APIs
  - [x] `napi_set_instance_data`
  - [x] `napi_get_instance_data`
- [x] Basic Node-API data types
  - [x] `napi_status`
  - [x] `napi_extended_error_info`
  - [x] `napi_env`
  - [x] `napi_value`
  - [x] `napi_threadsafe_function`
  - [x] `napi_threadsafe_function_release_mode`
  - [x] `napi_threadsafe_function_call_mode`
  - [x] Node-API memory management types
    - [x] `napi_handle_scope`
    - [x] `napi_escapable_handle_scope`
    - [x] `napi_ref`
    - [x] `napi_type_tag`
    - [x] `napi_async_cleanup_hook_handle`
  - [x] Node-API callback types
    - [x] `napi_callback_info`
    - [x] `napi_callback`
    - [x] `napi_finalize`
    - [x] `napi_async_execute_callback`
    - [x] `napi_async_complete_callback`
    - [x] `napi_threadsafe_function_call_js`
    - [x] `napi_async_cleanup_hook`
- [x] Error handling
  - [x] Return values
    - [x] `napi_get_last_error_info`
  - [x] Exceptions
    - [x] `napi_throw`
    - [x] `napi_throw_error`
    - [x] `napi_throw_type_error`
    - [x] `napi_throw_range_error`
    - [x] `node_api_throw_syntax_error`
    - [x] `napi_create_error`
    - [x] `napi_create_type_error`
    - [x] `napi_create_range_error`
    - [x] `node_api_create_syntax_error`
    - [x] `napi_get_and_clear_last_exception`
    - [x] `napi_is_exception_pending` (stubbed)
    - [x] `napi_fatal_exception`
  - [x] Fatal errors
    - [x] `napi_fatal_error`
- [ ] Object lifetime management
  - [ ] Making handle lifespan shorter than that of the native method
    - [x] `napi_open_handle_scope`
    - [x] `napi_close_handle_scope`
    - [ ] `napi_open_escapable_handle_scope` (stubbed)
    - [ ] `napi_close_escapable_handle_scope` (stubbed)
    - [ ] `napi_escape_handle` (stubbed)
  - [ ] References to objects with a lifespan longer than that of the native method
    - [ ] `napi_create_reference` (stubbed)
    - [ ] `napi_delete_reference` (stubbed)
    - [ ] `napi_reference_ref` (stubbed)
    - [ ] `napi_reference_unref` (stubbed)
    - [ ] `napi_get_reference_value` (stubbed)
  - [ ] Cleanup on exit of the current Node.js instance
    - [ ] `napi_add_env_cleanup_hook` (stubbed)
    - [ ] `napi_remove_env_cleanup_hook` (stubbed)
    - [ ] `napi_add_async_cleanup_hook`
    - [ ] `napi_remove_async_cleanup_hook`
- [x] Module registration
  - [x] `napi_module_register`
- [x] Working with JavaScript values
  - [x] Enum types
    - [x] `napi_key_collection_mode`
    - [x] `napi_key_filter`
    - [x] `napi_key_conversion`
    - [x] `napi_valuetype`
    - [x] `napi_typedarray_type`
  - [x] Object creation functions
    - [x] `napi_create_array`
    - [x] `napi_create_array_with_length`
    - [x] `napi_create_arraybuffer`
    - [x] `napi_create_buffer`
    - [x] `napi_create_buffer_copy`
    - [x] `napi_create_date`
    - [x] `napi_create_external`
    - [x] `napi_create_external_arraybuffer` 
    - [x] `napi_create_external_buffer`
    - [x] `napi_create_object`
    - [x] `napi_create_symbol`
    - [x] `napi_create_typedarray`
    - [x] `napi_create_dataview`
  - [x] Functions to convert from C types to Node-API
    - [x] `napi_create_int32`
    - [x] `napi_create_uint32`
    - [x] `napi_create_int64`
    - [x] `napi_create_double`
    - [x] `napi_create_bigint_int64`
    - [x] `napi_create_bigint_uint64`
    - [x] `napi_create_bigint_words`
    - [x] `napi_create_string_latin1`
    - [x] `napi_create_string_utf16`
    - [x] `napi_create_string_utf8`
  - [x] Functions to convert from Node-API to C types
    - [x] `napi_get_array_length`
    - [x] `napi_get_arraybuffer_info`
    - [x] `napi_get_buffer_info`
    - [x] `napi_get_prototype`
    - [x] `napi_get_typedarray_info`
    - [x] `napi_get_dataview_info`
    - [x] `napi_get_date_value`
    - [x] `napi_get_value_bool`
    - [x] `napi_get_value_double`
    - [x] `napi_get_value_bigint_int64`
    - [x] `napi_get_value_bigint_uint64`
    - [x] `napi_get_value_bigint_words`
    - [x] `napi_get_value_external`
    - [x] `napi_get_value_int32`
    - [x] `napi_get_value_int64`
    - [x] `napi_get_value_string_latin1`
    - [x] `napi_get_value_string_utf8`
    - [x] `napi_get_value_string_utf16`
    - [x] `napi_get_value_uint32`
  - [x] Functions to get global instances
    - [x] `napi_get_boolean`
    - [x] `napi_get_global`
    - [x] `napi_get_null`
    - [x] `napi_get_undefined`
- [ ] Working with JavaScript values and abstract operations
  - [x] `napi_coerce_to_bool`
  - [x] `napi_coerce_to_number`
  - [x] `napi_coerce_to_object`
  - [x] `napi_coerce_to_string`
  - [x] `napi_typeof`
  - [ ] `napi_instanceof` (https://github.com/denoland/rusty_v8/pull/879)
  - [x] `napi_is_array`
  - [x] `napi_is_arraybuffer`
  - [x] `napi_is_buffer`
  - [x] `napi_is_date`
  - [x] `napi_is_error`
  - [x] `napi_is_typedarray`
  - [x] `napi_is_dataview`
  - [x] `napi_strict_equals`
  - [x] `napi_detach_arraybuffer`
  - [x] `napi_is_detached_arraybuffer`
- [ ] Working with JavaScript properties
  - [x] Structures
    - [x] `napi_property_attributes`
    - [x] `napi_property_descriptor`
  - [ ] Functions
    - [x] `napi_get_property_names`
    - [ ] `napi_get_all_property_names` (needs v8 binding)
    - [x] `napi_set_property`
    - [x] `napi_get_property`
    - [x] `napi_has_property`
    - [x] `napi_delete_property`
    - [ ] `napi_has_own_property` (needs v8 binding)
    - [x] `napi_set_named_property`
    - [x] `napi_get_named_property`
    - [x] `napi_has_named_property`
    - [x] `napi_set_element`
    - [x] `napi_get_element`
    - [x] `napi_has_element`
    - [x] `napi_delete_element`
    - [x] `napi_define_properties` (incomplete)
    - [ ] `napi_object_freeze` (needs v8 binding)
    - [ ] `napi_object_seal` (needs v8 binding)
- [ ] Working with JavaScript functions
  - [x] `napi_call_function`
  - [x] `napi_create_function`
  - [x] `napi_get_cb_info`
  - [ ] `napi_get_new_target` (needs v8 binding)
  - [x] `napi_new_instance`
- [ ] Object wrap
  - [x] `napi_define_class` (TODO: proper getter/setters)
  - [x] `napi_wrap`
  - [x] `napi_unwrap`
  - [x] `napi_remove_wrap`
  - [ ] `napi_type_tag_object`
  - [ ] `napi_check_object_type_tag`
  - [ ] `napi_add_finalizer`
- [ ] Simple asynchronous operations
  - [ ] `napi_create_async_work` (stubbed)
  - [ ] `napi_delete_async_work` (stubbed)
  - [ ] `napi_queue_async_work` (stubbed)
  - [ ] `napi_cancel_async_work` (stubbed)
- [ ] Custom asynchronous operations
  - [ ] `napi_async_init`
  - [ ] `napi_async_destroy`
  - [ ] `napi_make_callback`
  - [ ] `napi_open_callback_scope`
  - [ ] `napi_close_callback_scope`
- [x] Version management
  - [x] `napi_get_node_version`
  - [x] `napi_get_version`
- [ ] Memory management
  - [ ] `napi_adjust_external_memory` (stubbed) (needs v8 binding) https://github.com/denoland/rusty_v8/pull/880
- [x] Promises
  - [x] `napi_create_promise`
  - [x] `napi_resolve_deferred`
  - [x] `napi_reject_deferred`
  - [x] `napi_is_promise`
- [x] Script execution
  - [x] `napi_run_script`
- ~~libuv event loop~~ (Not possible)
  - ~~`napi_get_uv_event_loop`~~
- [ ] Asynchronous thread-safe function calls
  - [ ] `napi_call_threadsafe_function`
  - [ ] `napi_create_threadsafe_function`
  - [ ] `napi_get_threadsafe_function_context`
  - [ ] `napi_call_threadsafe_function`
  - [ ] `napi_acquire_threadsafe_function`
  - [ ] `napi_release_threadsafe_function`
  - [ ] `napi_ref_threadsafe_function`
  - [ ] `napi_unref_threadsafe_function`
- [ ] Miscellaneous utilities
  - [x] `node_api_get_module_file_name`

**Comment by sno2** [comment]
Is this repo description supposed to say `[wip] Implementation of N-API for deno_core`?  The name is `napi-rusty-v8` so maybe this could just be generalized to `[wip] Implementation of N-API for integration with rusty_v8`?
